deployment:
  tasks:
    - export DEPLOYPATH=/home/ifthesel/public_html/
    - /bin/cp index.html $DEPLOYPATH
    - /bin/cp -R data $DEPLOYPATH
    - /bin/cp -R pages $DEPLOYPATH
    - /bin/cp -R css $DEPLOYPATH
    - /bin/cp -R js $DEPLOYPATH
    - /bin/cp -R assets $DEPLOYPATH
